### ISSUE TITLE
Realtime data

### ISSUE THREAD

**Issue by kaualandi** [smappaa/canvas-ecg-display#1]
Hello, how are you? I was wondering if you were interested in implementing real-time data in your code. We have the data in a websocket and I'd like to help you.

**Comment by smappaa** [comment]
Hi!

I'm open to the idea. What kind of real-time data were you thinking of? If you're suggesting using real ECG signal we'd have to re-implement a lot of the JS, because the rhythms etc. are pretty much hard coded right now. But I wouldn't necessarily be opposed to that.

Regards, Samuli

**Comment by kaualandi** [comment]
These are real curves from real monitors, they have been integrated with them, and I have attached an example of the feedback that comes from the websocket. I think it would be an incredible thing to increase and your partnership would be a great help.

[example-monitor-response-ws.json](https://github.com/smappaa/canvas-ecg-display/files/15095724/example-monitor-response-ws.json)

**Comment by smappaa** [comment]
I'll check it out!

**Comment by smappaa** [comment]
I'm actually very interested to implement this into a live solution. I've been brainstorming with the approaches and actually I started working on it based on the JSON you submitted. I'm a beginner so there are many things I'm doing for the first time here, but I'm learning as we go. I have a few questions:
1) Should I work on the repo you forked and do pull requests there?
2) The JSON you linked has 256 data points per 1000 ms; is this a steady stream or will the number of data points per second change?
3) What are the coordinates' range (0-300?), or what are they based on? (this doesn't really matter though, I think I will justify the data to fit well on the canvas anyway)
4) Does the data gathering from the websocket work in a way that the data comes in packages of 5 seconds, or can we affect this?
5) Does it matter if there's a few seconds delay between the time the data was spit out of the websocket and the time it will be drawn?

Thanks!

**Comment by kaualandi** [comment]
Hello, I'm glad to hear from you and to know that you're interested in this implementation.

The data from the websocket arrive in a continuous stream of 256 points per second. We have chosen to bundle them into 5-second packets, resulting in 1280 points. However, this can be easily customized. What remains constant is the scale of 256 points for each second.
Regarding the data range (0-300), it can vary depending on the equipment used and the type of signal emitted. Normalizing this data might be a good approach.
A slight delay between the data emission and its display is inevitable, but the smaller this delay, the better the solution.

Feel free to ask any questions you might have.
Thank you for your interest, and I am here to help.

**Comment by smappaa** [comment]
Stream of 256 points per second in packages of 5 seconds sounds great! I'm making good progress already, and I think we will soon have a minimum viable product! Now, how can I use this websocket we're talking about?

**Comment by smappaa** [comment]
I just created a new repository for the project: [live-canvas-ecg-display](https://github.com/smappaa/live-canvas-ecg-display). Most of the logic is in place to visualize the signal.
